name: main

on:
  push:
    branches:
      - main

jobs:
  services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Show Service builder
        uses: docker/setup-buildx-action@v1
        id: show_builder
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Show Service
        id: show_docker_build
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.show_builder.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: uehreka/mayfly-show:${{ steps.extract_branch.outputs.branch }}